### ISSUE TITLE
MAIN_BOARD_32 : V1.20 : UART 1 and UART 2 seems to be physicalled connected

### ISSUE THREAD

**Issue by svanacker** [svanacker/cen-electronic-schema#11]
When I write something in UART 2, I got some data in UART 1.
It's not the same when I use UART 5 and 6

**Comment by f4deb** [comment]
Test with MAIN_BOARD V1-30
When I reset the Pic, some data from UART2 are transferred on UART1.
The problem disappears when I add pull down resistor on PIN 51 and PIN 32 from PIC32

**Comment by svanacker** [comment]
It's not only on startup but after reset too, in normal running mode. Does it disappear too ?

**Comment by f4deb** [comment]
Pull up resistor added on Uart TX. This seems to solve the problem.
